### ISSUE TITLE
JSON trailing comma issue as requested

### ISSUE THREAD

**Issue by jbrownson** [chenglou/reason-react-example#13]
There's a comment at the top of `bsconfig.json`: 

```
This is the BuckleScript configuration file. Note that this is a comment;
  BuckleScript comes with a JSON parser that supports comments and trailing
  comma. If this screws with your editor highlighting, please tell us by filing
  an issue!
```

I'm using VSCode and it red-squiggly-underlines the trailing commas. Doesn't really bother me but I'm posing since the comment asks me to.

**Comment by cxa** [comment]
This extension may help: https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-json5

**Comment by chenglou** [comment]
Sorry for the wait! Done.
