### ISSUE TITLE
Add to README: Install OCaml

### ISSUE THREAD

**Issue by sugargreenbean** [chenglou/reason-react-example#18]
Unfortunately, this was not obvious to me...So I think adding just a short line to the README with a link to: http://www.ocaml.org/docs/install.html would be very helpful for someone completely new who wants to pick up reason-react!

**Comment by jordwalke** [comment]
hi @sugargreenbean, was it necessary to install ocaml to use reason-react-example?

**Comment by sugargreenbean** [comment]
@jordwalke You're right! Just tested again, not necessary. :) Thanks!

**Comment by jordwalke** [comment]
No problem.
