### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by stephensong** [chenglou/reason-react-example#28]
Followed the install instructions, but got this when I ran "npm run build"

ERROR in ./lib/js/src/todomvc/app.js
Module not found: Error: Cannot resolve module 'director/build/director' in /Users/gary/dev/reason-react-example/lib/js/src/todomvc

Ideas? 

thanks.

**Comment by chenglou** [comment]
Your dependencies might be out of date? Do you have a package-lock file or something?

**Comment by chenglou** [comment]
We've now moved away from director, so this should be solved too
