### ISSUE TITLE
Initial build fail 

### ISSUE THREAD

**Issue by DCKT** [chenglou/reason-react-example#42]
Hello there,

After `npm i`, I tried to build the project but I got this error coming from `bs-fetch` dependency : 
<img width="1356" alt="capture d ecran 2018-05-21 a 15 15 48" src="https://user-images.githubusercontent.com/1548421/40309465-e2d2c46c-5d09-11e8-895b-8c2bbbe78fec.png">

I think I'm up-to date, how can I check that ? 
Thanks for your work 😄

**Comment by jihchi** [comment]
It's related to BuckleScript 3.1.0.

You could downgrade `bs-platform` to 3.0 as temporary workaround.

reasonml-community/bs-fetch#17

**Comment by DCKT** [comment]
@jihchi Thanks for your answer, I'll downgrade for now

**Comment by jihchi** [comment]
Now, you could use BS 3.1.0 with bs-fetch [0.3.0](https://github.com/reasonml-community/bs-fetch/issues/17#issuecomment-390661132)
